### ISSUE TITLE
Invalid release "vv1.8.0" on bosh.io

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/python-buildpack-release#4]
Hi Python Buildpack Developers,

there is an invalid or corrupted release on bosh.io:
https://bosh.io/releases/github.com/cloudfoundry/python-buildpack-release?all=1#vv1.8.0

This version is currently marked as "latest" and blocks the update of the python-buildpack in the cf-deployment release process:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/update-releases/resources/python-buildpack-release

Can you please remove that version from bosh.io? Or fix the version number?

Thanks and Best Regards,

  Jochen.

**Comment by arjun024** [comment]
@jochenehret This was removed from bosh.io (See https://github.com/bosh-io/releases-index/pull/4) but it looks like their automation added it back. That version is also currently not present in buildpack bosh-release repo either (See https://github.com/cloudfoundry/python-buildpack-release/tags)
Could you reach out to the bosh.io admins? The maintainers of the buildpack do not have privileges on bosh.io

cc @brayanhenao @thitch97 @robdimsdale

**Comment by jochenehret** [comment]
python-buildpack update is running again: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-python-buildpack/builds/7

**Comment by jochenehret** [comment]
Corrupt release appeared again on bosh.io and is blocking the cf-deployment update:
https://bosh.io/releases/github.com/cloudfoundry/python-buildpack-release?all=1
Can you please check?

**Comment by jpalermo** [comment]
You need to remove the bad release from [here](https://github.com/cloudfoundry/python-buildpack-release/blob/master/releases/python-buildpack/python-buildpack-v1.8.0.yml) or automation will just keep recreating it.

**Comment by jpalermo** [comment]
Re-updated the bosh.io index, should be gone now, hopefully for good
